core/urls.py
# coding=utf-8

from .views import *
from django.conf.urls import url, include
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^core/$', TemplateView.as_view(template_name="core.html")),
]

order/urls.py
from order.views import *
from rest_framework import routers
from django.urls import path, include

router = routers.DefaultRouter()
router.register(r'orders_list', OrderViewSet)

urlpatterns = [
    path(r'', include(router.urls))
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from dishes.views import *
from order.views import *
from accounts.views_api import *
from dishes.views_api import *
from order.views_api import *
from rest_framework import routers, serializers, viewsets

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('accounts.urls')),
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('ingredientsedit/<int:pk>/', IngredientUpdateView.as_view()),
    path('addingredient/', AddNewIngredientView.as_view()),
    path('ingredients/', IngredientListView.as_view()),
    path('dishedit/<int:pk>/', DishUpdateView.as_view()),
    path('dishadd/', AddNewDishView.as_view()),
    path('dishes/', DishListView.as_view()),
    path('drinkedit/<int:pk>/', DrinkUpdateView.as_view()),
    path('drinkadd/', AddNewDrinkView.as_view()),
    path('drinks/', DrinkListView.as_view()),
    path('dish/', DishView.as_view()),
    path('changepricedish/', ChangePriceDishView.as_view()),
    path('dishes/addpizza/', AddDishView.as_view()),
    path('adddrink/', AddDrinkView.as_view()),
    path('order/', OrderView.as_view()),
    path('changeinstance/<int:pk>/', InstanceUpdateView.as_view()),
    path('makeorder/<int:pk>/', MakeOrderView.as_view()),
    path('order_sucess/', AboutView.as_view()),
    # API URLS
    path('ap1i/', UserApiView.as_view()),
    path('createuser/', CreateUserApiView.as_view()),
    path('pizzas/', DishApiView.as_view()),
    path('orders/', OrderApiView.as_view()),
    path('make_order/', PizzaToOrderApiView.as_view()),
    path('dish_api/', include('dishes.urls')),
    path('order_api/', include('order.urls'))
]

if settings.DEBUG:
    urlpatterns += [
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += staticfiles_urlpatterns()

dishes/models.py
from django.db import models
from decimal import Decimal


class BaseItem(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0)

    class Meta:
        abstract = True


class Ingredient(BaseItem):
    is_vegan = models.BooleanField(default=False)
    is_meat = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Ингридиент'
        verbose_name_plural = 'Ингридиенты'

    def __str__(self):
        return self.name


class Dish(BaseItem):
    ingredients = models.ManyToManyField(Ingredient, blank=True, null=True)
    dish_img = models.ImageField(
        upload_to='media/', max_length=255,
        blank=True, null=True
    )
    alt = models.CharField(blank=True, null=True, max_length=512)

    class Meta:
        verbose_name = 'Блюдо'
        verbose_name_plural = 'Блюда'

    def __str__(self):
        return self.name

    @staticmethod
    def change_price(price):
        dishes = Dish.objects.all()
        for dish in dishes:
            dish.price += price
            dish.save()

    def create_order(self, count):
        return InstanceDish.objects.create(
                name=self.name,
                price=self.price,
                dish=self,
                count=count
            )

    def get_serialize_data(self):
        return{
            'name': self.name,
            'price': self.price,
            'image': self.dish_img.url,
            'ingedients': list(self.ingredients.all().values_list('name', flat=True))
        }


class Drink(BaseItem):
    drink_img = models.ImageField(
        upload_to='media/', max_length=255,
        blank=True, null=True
    )
    alt = models.CharField(blank=True, null=True, max_length=512)

    class Meta:
        verbose_name = 'Напиток'
        verbose_name_plural = 'Напитки'

    def __str__(self):
        return self.name

    def create_order(self, count):
        return InstanceDrink.objects.create(
                name=self.name,
                price=self.price,
                drink=self,
                count=count
            )


class InstanceDrink(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    count = models.PositiveIntegerField(default=1)
    drink = models.ForeignKey(
        Drink, related_name='drinks', null=True,
        blank=True, on_delete=models.SET_NULL
    )

    class Meta:
        verbose_name = 'Корзина напитки'
        verbose_name_plural = 'Корзина напитки'

    def __str__(self):
        return 'Напиток: {}, цена: {}, количество: {}, сумма: {}'.format(
            self.name,
            str(self.price),
            str(self.count),
            str(self.price * self.count)
            )


class InstanceDish(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    count = models.PositiveIntegerField(default=1)
    dish = models.ForeignKey(
        Dish, related_name='dishes', null=True,
        blank=True, on_delete=models.SET_NULL
    )

    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзина'

    def __str__(self):
        return 'Блюдо: {}, цена: {}, количество: {}, сумма: {}'.format(
            self.name,
            str(self.price),
            str(self.count),
            str(self.price * self.count)
            )

order/models.py
from django.db import models
from dishes.models import Dish, Drink, InstanceDish, InstanceDrink
from accounts.models import User
from phonenumber_field.modelfields import PhoneNumberField
from accounts.views_api import UserApiView
from accounts.models import User


class Order(models.Model):
    dishes = models.ManyToManyField(InstanceDish, blank=True, null=True)
    drinks = models.ManyToManyField(InstanceDrink, blank=True, null=True)
    date_create = models.DateTimeField(auto_now_add=True)
    full_price = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    user_profile = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    phone_number = PhoneNumberField(null=True, blank=True)
    first_name = models.CharField(max_length=255, null=True, blank=True)
    adress = models.CharField(max_length=255, null=True, blank=True)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return '{}'.format(self.id)

    def dishes_list(self):
        return ([dish.name for dish in self.dishes.all()])

    def calculate_price(self):
        self.full_price = 0
        for dish in self.dishes.all():
            self.full_price += dish.price * dish.count
            print(self.full_price, dish.price, dish.count)
        for drink in self.drinks.all():
            self.full_price += drink.price * drink.count
        self.save()

    def get_serialize_data(self):
        print(self.user_profile.id)
        return{
            'dishes': list(self.dishes.all().values_list('name', 'count', 'price')),
            'date': self.date_create,
            'full_price': self.full_price,
            'phone': str(self.phone_number),
            'first_name': self.first_name,
            'adress': self.adress
        }

order/forms.py
from django import forms
from django.forms import ModelForm
from order.models import Order
from dishes.models import *


class DishForm(forms.Form):
    dish_id = forms.IntegerField()
    count = forms.IntegerField()


class ChangeInstanceForm(ModelForm):
    class Meta:
        model = InstanceDish
        fields = ['count']


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['phone_number', 'first_name', 'adress']


class DrinkForm(forms.Form):
    drink_id = forms.IntegerField()
    count = forms.IntegerField()

order/views.py
from django.shortcuts import render
from order.models import *
from django.views.generic.edit import UpdateView, FormView
from django.views.generic import TemplateView, ListView, View, FormView
from order.forms import *
from dishes.models import *
from rest_framework import routers, serializers, viewsets
from order.serializers import OrderSerializer
from .tasks import *
from dishes.tasks import *


class AddDishView(FormView):
    template_name = "dish_list.html"
    form_class = DishForm
    success_url = '/dishes/'

    def form_valid(self, form):
        dish_id = form.cleaned_data.get('dish_id')
        # dish = Dish.objects.get(id=form.cleaned_data.get('dish_id'))
        count = form.cleaned_data.get("count")
        # instance = Dish.create_order(dish, count)
        # order, created = Order.objects.get_or_create()
        # order.dishes.add(instance)
        # order.calculate_price()
        order_add.delay(dish_id, count)
        parsing_pizzas.delay()
        return super().form_valid(form)


class AddDrinkView(FormView):
    template_name = 'drink_list.html'
    form_class = DrinkForm
    success_url = '/drinks/'

    def form_valid(self, form):
        drink = Drink.objects.get(id=form.cleaned_data.get('drink_id'))
        count = form.cleaned_data.get("count")
        instance = Drink.create_order(drink, count)
        order, created = Order.objects.get_or_create()
        order.drinks.add(instance)
        order.calculate_price()
        return super().form_valid(form)


class OrderView(ListView):
    model = Order
    template_name = 'order.html'


class InstanceUpdateView(UpdateView):
    form_class = ChangeInstanceForm
    model = InstanceDish
    template_name = 'send.html'
    success_url = '/order'

    def form_valid(self, form):
        instance = super().form_valid(form)
        order = Order.objects.get()
        order.calculate_price()
        return instance


class MakeOrderView(UpdateView):
    form_class = OrderForm
    model = Order
    template_name = "make_order.html"
    success_url = '/order_sucess/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class OrderViewSet(viewsets.ModelViewSet):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nothing+You+Could+Do" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">

    
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="index.html"><span class="flaticon-pizza-1 mr-1"></span>Pizza<br><small>Delicious</small></a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item"><a href="index.html" class="nav-link">Home</a></li>
	          <li class="nav-item"><a href="/dishes" class="nav-link">PIZZAS</a></li>
	          <li class="nav-item"><a href="/drinks" class="nav-link">DRINKS</a></li>
	          <li class="nav-item active"><a href="/order" class="nav-link">ORDERS</a></li>
	          <li class="nav-item"><a href="about.html" class="nav-link">About</a></li>
	          <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
	        </ul>
	      </div>
		  </div>
	  </nav>

    {% block main %}{% endblock %}

<section class="ftco-intro">
  <div class="container-wrap">
    <div class="wrap d-md-flex">
      <div class="info">
        <div class="row no-gutters">
          <div class="col-md-4 d-flex ftco-animate">
            <div class="icon"><span class="icon-phone"></span></div>
            <div class="text">
              <h3>pizzeria's phone nunber</h3>
              <p>text text text</p>
            </div>
          </div>
          <div class="col-md-4 d-flex ftco-animate">
            <div class="icon"><span class="icon-my_location"></span></div>
            <div class="text">
              <h3>pizzeria's address str.</h3>
              <p>pizzeria adress city</p>
            </div>
          </div>
          <div class="col-md-4 d-flex ftco-animate">
            <div class="icon"><span class="icon-clock-o"></span></div>
            <div class="text">
              <h3>pizzeria's days of work</h3>
              <p>open hours</p>
            </div>
          </div>
        </div>
      </div>
      <div class="social d-md-flex pl-md-5 p-4 align-items-center">
        <ul class="social-icon">
          <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
          <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
          <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
        </ul>
      </div>
    </div>
  </div>
</section>
<br>
<br>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
    <script src="{% static 'js/scrollax.min.js' %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="{% static 'js/google-map.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script> 
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

project/templates/change_price.html
<ul>
	<a href="/changepricedish">Повысить цену</a>
</ul>

project/templates/change_price_form.html
<form method="post">{% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Повысить цену">
</form>

project/templates/dish_add.html
<a href="/dishadd">Добавить новое блюдо</a>

project/templates/dish_list.html
{% extends "base.html" %}

{% block main %}

<section class="home-slider owl-carousel img">
  <div class="slider-item" style="background-image: url(/static/images/image_3.jpg);">
      <div class="overlay"></div>
        <div class="container">
            <div class="row slider-text justify-content-center align-items-center">
              <div class="col-md-7 col-sm-12 text-center ftco-animate">
                <h1 class="mb-3 mt-5 bread">Our Menu</h1>
              </div>
            </div>
        </div>
      </div>
	</div>
</section>

<div class="container-wrap">
  <div class="row no-gutters d-flex">
    {% for dish in dish_list %}
      <div class="col-lg-4 d-flex ftco-animate"">
        <div class="services-wrap d-flex" ">
          {% if dish.id == 21 or dish.id == 5 or dish.id == 19 or dish.id == 14 or dish.id == 24 or dish.id == 33 or dish.id == 16 or dish.id == 22 or dish.id == 18 or dish.id == 29 or dish.id == 35 or dish.id == 12 or dish.id == 27 or dish.id == 31 or dish.id == 25 or dish.id == 10 or dish.id == 17%}
            <a href="#" class="img order-lg-last" style="background-image: url({{ dish.dish_img.url }});"></a>
          {% else %}
            <a href="#" class="img" style="background-image: url({{ dish.dish_img.url }});"></a>
          {% endif %}
            <div class="text p-4">
              <h3>{{ dish.name }}</h3>
              <p>{{ dish.alt }}</p>
              <p class="price"><span>{{dish.price}}</span>
              <form method="post" action="addpizza/">{% csrf_token %}
              <input type="number" name="dish_id" value="{{ dish.id }}" hidden="dish.id">
              <input type ="number" class="ml-2 btn btn-white btn-outline-white" name="count" value="{{ dish.count }}" style="width: 65px; height: 32px;">
              <button type="submit" class="btn btn-primary" value="Order">В корзину</button>
              </form>
            </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div> 

<div class="row mt-5">
  <div class="col text-center">
    <div class="block-27">
      <ul>
        {% if page_obj.has_previous %}
        <li>
          <a href="/dishes/?page={{ page_obj.previous_page_number }}">&laquo;</a>
        </li>
        {% endif %}
        {% if page_obj.number == 1 %}
        <li class="active">
          <a href="/dishes/?page=1">1</a>
        </li>
        {% else %}
        <li>
          <a href="/dishes/?page=1">1</a>
        </li>
        {% endif %}
        {% if page_obj.number == 2 %}
        <li class="active">
          <a href="/dishes/?page=2">2</a>
        </li>
        {% else %}
        <li>
          <a href="/dishes/?page=2">2</a>
        </li>
        {% endif %}
        {% if page_obj.number == 3 %}
        <li class="active">
          <a href="/dishes/?page=3">3</a>
        </li>
        {% else %}
        <li>
          <a href="/dishes/?page=3">3</a>
        </li>
        {% endif %}
        {% if page_obj.has_next %}
        <li>
          <a href="/dishes/?page={{ page_obj.next_page_number }}">&raquo;</a>
        </li>
        {% endif %}
        </li>
      </ul>
    </div>
  </div>
</div>
<br>

{% endblock %} 

project/templates/dishes.html
{% extends "base.html" %}
{% block main %}
<h2>БЛЮДА</h2>

<nav aria-label="Page navigation example">
	  <ul class="pagination">
	    <li class="page-item"><a class="page-link" href="/dishes/?ordering=name">по алфавиту</a></li>
	    <li class="page-item"><a class="page-link" href="/dishes/?ordering=price">от дешевых к дорогим</a></li>
	    <li class="page-item"><a class="page-link" href="/dishes/?ordering=-price">от дорогих к дешевым</a></li>
	  </ul>
</nav>

<div class="order_area">
        <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="section_title mb-70">
                            <h3>Popular Orders</h3>
                        </div>
                    </div>
                </div>
            <div class="row">
            	{% for dish in dish_list %}
                <div class="col-xl-4 col-md-6">
                    <div class="single_order">
                        <div class="order_thumb">
                            <img class="myImage" src="{{ dish.dish_img.url }}">
                            <div class="order_prise">
                                <span>10.00</span>
                            </div>
                        </div>
                        <div class="order_info">
                            <h3>{{ dish.name }}</h3>
                            <p>{% if dish.alt|length < 33 %}
                            {{dish.alt}}<br><br><br>
                            {%elif dish.alt|length < 78%}
                            {{dish.alt}}<br><br>
                            {%else%}
                            {{dish.alt}}{{dish.alt|length}}
                            {%endif%}                            </p>
                            <a href="#" class="boxed_btn">Order Now!</a>
                        </div>
                    </div>
                </div>
	{% endfor %}
</div>
<div class="center">
	<ul><nav aria-label="Page navigation example">
	  <ul class="pagination">
	    <li class="page-item"><a class="page-link" href="/dishes/?page=1">1</a></li>
	    <li class="page-item"><a class="page-link" href="/dishes/?page=2">2</a></li>
	    <li class="page-item"><a class="page-link" href="/dishes/?page=3">3</a></li>
	  </ul>
	</nav></ul>
</div>

{% endblock %}

project/templates/drink_add.html
<a href="/drinkadd">Добавить напиток</a>

project/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block head_title %}Index page{% endblock %}

{% block main %}
<div class="container">
    <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
    </div>
</div>
{% endblock %}

project/templates/ingredient_add.html
<a href="/addingredient">Добавить новый ингридиент</a>

project/templates/ingredients_list.html
{% extends "base.html" %}

{% block main %}

<h2>ИНГРИДИЕНТЫ</h2>

	<ul>
		{% for ingredient in ingredient_list|dictsort:"price" %}
			<li>{{ ingredient.name|capfirst }}  {{ ingredient.price }} - <a href="/ingredientsedit/{{ ingredient.id }}/">изменить</a> </li>
		{% endfor %}
	</ul>

	<ul>
		{% if ingredient_list %}
			Количество ингридиентов: {{ ingredient_list|length }}
		{% else %}
			Нет ингридиентов.
		{% endif %}
	</ul>

	<ul>
	{% include "ingredient_add.html" %}
	</ul>

{% endblock %}

project/templates/order.html
{% extends "base.html" %}

{% block main %}

{% comment %} <div>
	<ul>
		{% for order in order_list %}
			<li> Заказ № {{ order.id }}<br>
				<br>
			{% for dish in order.dishes.all %}
      {{dish.dish.dish_img.url}}
				{{ dish.name }} {{ dish.count }} {% widthratio dish.price 1 dish.count %} - <a href="/changeinstance/{{ dish.id }}/">редактировать</a><br>
			{% endfor %}
				<br>
			{% for drink in order.drinks.all %} 
				{{ drink.name}} {{ drink.count }} {% widthratio drink.price 1 drink.count %}<br>
			{% endfor %}
			сумма заказа: {{ order.full_price }}<br>
			дата заказа: {{ order.date_create }}<br></li>
			<br>
			<p><a href="/makeorder/{{ order.id }}/"><button>оформить заказ</button></a></p>
		{% endfor %}		
	</ul>
</div> {% endcomment %}
<div class="container">
    		<div class="row justify-content-center mb-5 pb-3 mt-5 pt-5">
          <div class="col-md-7 heading-section text-center ftco-animate">
            <h2 class="mb-4">{% for order in order_list %} 
            Заказ № {{ order.id }}
            {% endfor %}</h2>
            <p class="flip"><span class="deg1"></span><span class="deg2"></span><span class="deg3"></span></p>
          </div>
        </div>
<div class="row">
{% for order in order_list %}
    <div class="col-md-6">
      {% for dish in order.dishes.all %}
      <div class="pricing-entry d-flex ftco-animate">
        <div class="img" style="background-image: url({{ dish.dish.dish_img.url }});"></div>
          <div class="desc pl-3">
            <div class="d-flex text align-items-center">
              <h3><span>{{dish.name}}</span></h3>
              <span class="price">{% widthratio dish.price 1 dish.count %}.00</span>
            </div>
			<div class="d-block">
				<p>Количество: {{ dish.count }}</p>
			</div>
          </div>
        </div>
    {% endfor %}
	{% for drink in order.drinks.all %}
      <div class="pricing-entry d-flex ftco-animate">
        <div class="img" style="background-image: url({{ drink.drink.drink_img.url }});"></div>
          <div class="desc pl-3">
            <div class="d-flex text align-items-center">
              <h3><span>{{ drink.name }}</span></h3>
              <span class="price">{% widthratio drink.price 1 drink.count %}.00</span>
            </div>
			<div class="d-block">
				<p>Количество: {{ drink.count }}</p>
			</div>
          </div>
        </div>
    {% endfor %}
    	сумма заказа: {{ order.full_price }} uah<br>
			дата заказа: {{ order.date_create }}<br>
			<br>
			<p><a href="/makeorder/{{ order.id }}/"><button class="btn btn-primary">оформить заказ</button></a></p>
		{% endfor %}
    </div>
  </div>
</div>
<br>
{% endblock %}  

project/templates/send.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>